name: PocketVote
main: ProjectInfinity\PocketVote\PocketVote
version: 2.1.0
api: [3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
author: ProjectInfinity
permissions:
  pocketvote.admin:
    description: "Allows player to manage PocketVote"
    default: op
